import { Image } from "expo-image";
import { useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { AppShell, DemoPill, EVENT_IMAGES, PALETTE, PageHeader, ScreenLoading } from "@/components/velora-ui";
import { trpc } from "@/lib/trpc";
import { DEMO_BLOG_POSTS } from "@/shared/velora";

export default function Article(){const {slug}=useLocalSearchParams<{slug:string}>();const content=trpc.content.list.useQuery();const article:any=content.data?.find(item=>item.slug===slug) ?? DEMO_BLOG_POSTS.find(item=>item.slug===slug);if(!article)return <AppShell><PageHeader title="JOURNAL"/><View style={{padding:30}}><Text>Article not found.</Text></View></AppShell>;const body=(Array.isArray(article.body)?article.body:JSON.parse(article.body)) as string[];const faq=(article.faq ?? [{question:"Is this current availability?",answer:"No. This is a VÉLORA DEMO guide and does not confirm real-world availability."}]) as Array<{question:string;answer:string}>;const image=EVENT_IMAGES[article.imageKey as keyof typeof EVENT_IMAGES]||EVENT_IMAGES.hero;return <AppShell><SafeAreaView style={styles.safe} edges={["top","left","right"]}><PageHeader title="JOURNAL"/><ScrollView contentContainerStyle={styles.page}><Image source={image} contentFit="cover" style={styles.image}/><View style={styles.head}><View style={styles.meta}><DemoPill/><Text style={styles.cat}>{article.category.toUpperCase()}</Text></View><Text style={styles.title}>{article.title}</Text><Text style={styles.excerpt}>{article.excerpt}</Text><Text style={styles.byline}>VÉLORA JOURNAL · {article.publishedAt?new Date(article.publishedAt).toLocaleDateString():"DRAFT"}</Text></View><View style={styles.body}>{body.map((p,i)=><Text key={i} style={styles.para}>{p}</Text>)}</View><View style={styles.faq}><Text style={styles.faqTitle}>FREQUENTLY ASKED QUESTIONS</Text>{faq.map((item,i)=><View key={i} style={styles.faqItem}><Text style={styles.question}>{item.question}</Text><Text style={styles.answer}>{item.answer}</Text></View>)}</View><View style={styles.schema}><Text style={styles.schemaTitle}>SEARCH-FRIENDLY CONTENT</Text><Text style={styles.schemaText}>This article stores a clean URL, SEO title, meta description, editorial image key, internal record links, FAQ data and social-sharing-ready content fields. It only references VÉLORA database records.</Text></View></ScrollView></SafeAreaView></AppShell>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PALETTE.cream},page:{paddingBottom:108},image:{width:"100%",height:280},head:{padding:20},meta:{flexDirection:"row",alignItems:"center",gap:9},cat:{fontSize:9,fontWeight:"800",letterSpacing:.8,color:PALETTE.muted},title:{fontFamily:"Georgia",fontSize:31,lineHeight:35,letterSpacing:-.7,color:PALETTE.ink,marginTop:15},excerpt:{fontSize:14,lineHeight:20,color:PALETTE.muted,marginTop:13},byline:{fontSize:9,fontWeight:"800",letterSpacing:.8,color:PALETTE.champagne,marginTop:16},body:{padding:20,paddingTop:5,gap:18},para:{fontSize:14,lineHeight:22,color:PALETTE.ink},faq:{margin:20,padding:17,backgroundColor:PALETTE.nude},faqTitle:{fontSize:10,fontWeight:"800",letterSpacing:1,color:PALETTE.ink},faqItem:{marginTop:16,paddingTop:14,borderTopWidth:1,borderColor:"#D8CFBF"},question:{fontSize:13,fontWeight:"700",color:PALETTE.ink},answer:{fontSize:11,lineHeight:17,color:PALETTE.muted,marginTop:6},schema:{margin:20,marginTop:3,padding:16,borderLeftWidth:3,borderColor:PALETTE.champagne,backgroundColor:PALETTE.white},schemaTitle:{fontSize:9,fontWeight:"800",letterSpacing:.9,color:PALETTE.ink},schemaText:{fontSize:10,lineHeight:16,color:PALETTE.muted,marginTop:7}});
