import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { Link } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { AppShell, DemoPill, EVENT_IMAGES, PALETTE, PageHeader, ScreenLoading } from "@/components/velora-ui";
import { trpc } from "@/lib/trpc";
import { DEMO_BLOG_POSTS } from "@/shared/velora";

export default function Blog(){const {data:liveArticles}=trpc.content.list.useQuery();const data:any[] = liveArticles ?? DEMO_BLOG_POSTS.map((post,index)=>({ ...post,id:index+1,isDemo:true,status:"PUBLISHED" }));return <AppShell><SafeAreaView style={styles.safe} edges={["top","left","right"]}><PageHeader title="JOURNAL"/><ScrollView contentContainerStyle={styles.page}><Text style={styles.eyebrow}>THE VÉLORA JOURNAL</Text><Text style={styles.title}>EXPERIENCE,{`\n`}THOUGHTFULLY.</Text><Text style={styles.intro}>Catalog-grounded guides for selecting tickets and exploring the VÉLORA DEMO environment. The content engine never uses unverified event, price, availability or policy claims.</Text><View style={styles.list}>{data?.map(article=>{const image=EVENT_IMAGES[article.imageKey as keyof typeof EVENT_IMAGES]||EVENT_IMAGES.hero;return <Link key={article.id} href={{pathname:"/blog/[slug]",params:{slug:article.slug}} as any} asChild><View style={styles.card}><Image source={image} contentFit="cover" style={styles.image}/><View style={styles.cardContent}><View style={styles.cardMeta}><DemoPill/><Text style={styles.category}>{article.category.toUpperCase()}</Text></View><Text style={styles.articleTitle}>{article.title}</Text><Text numberOfLines={3} style={styles.excerpt}>{article.excerpt}</Text><View style={styles.read}><Text style={styles.readText}>READ ARTICLE</Text><MaterialIcons name="arrow-forward" size={16} color={PALETTE.ink}/></View></View></View></Link>})}</View></ScrollView></SafeAreaView></AppShell>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PALETTE.cream},page:{padding:20,paddingBottom:110},eyebrow:{fontSize:10,fontWeight:"800",letterSpacing:1.3,color:PALETTE.champagne,marginTop:25},title:{fontFamily:"Georgia",fontSize:37,lineHeight:40,letterSpacing:-1,color:PALETTE.ink,marginTop:7},intro:{fontSize:12,lineHeight:18,color:PALETTE.muted,marginTop:15,maxWidth:330},list:{marginTop:30,gap:15},card:{backgroundColor:PALETTE.white,borderWidth:1,borderColor:PALETTE.border},image:{width:"100%",height:185},cardContent:{padding:16},cardMeta:{flexDirection:"row",alignItems:"center",gap:8},category:{fontSize:9,fontWeight:"800",letterSpacing:.8,color:PALETTE.muted},articleTitle:{fontFamily:"Georgia",fontSize:21,lineHeight:24,color:PALETTE.ink,marginTop:12},excerpt:{fontSize:11,lineHeight:16,color:PALETTE.muted,marginTop:8},read:{marginTop:15,paddingTop:12,borderTopWidth:1,borderColor:PALETTE.border,flexDirection:"row",justifyContent:"space-between"},readText:{fontSize:9,fontWeight:"800",letterSpacing:.8,color:PALETTE.ink}});
