import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { AppShell, BrandMark, EmptyState, EventCard, PALETTE, ScreenLoading, SectionTitle } from "@/components/velora-ui";
import { CATEGORIES, CITIES, DEMO_EVENTS } from "@/shared/velora";
import { trpc } from "@/lib/trpc";

export default function EventsScreen() {
  const params = useLocalSearchParams<{ category?: string; city?: string }>();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState(params.category ?? "All");
  const [city, setCity] = useState(params.city ?? "All");
  const [sort, setSort] = useState("Recommended");
  const { data } = trpc.marketplace.events.useQuery({ query: query || undefined, category: category === "All" ? undefined : category, city: city === "All" ? undefined : city });
  const fallback = DEMO_EVENTS.filter((event) => (!query || `${event.title} ${event.artist} ${event.venue} ${event.city}`.toLowerCase().includes(query.toLowerCase())) && (category === "All" || event.category === category) && (city === "All" || event.city === city)).map((event, index) => ({ ...event, id: index + 1, startsAt: new Date(event.date) }));
  const events = useMemo(() => [...(data ?? fallback)].sort((a, b) => sort === "Date" ? new Date(a.startsAt).getTime() - new Date(b.startsAt).getTime() : sort === "Price Low → High" ? (a.fromPrice ?? 0) - (b.fromPrice ?? 0) : sort === "Price High → Low" ? (b.fromPrice ?? 0) - (a.fromPrice ?? 0) : Number(b.isVeloraPick) - Number(a.isVeloraPick)), [data, sort]);
  return <AppShell><SafeAreaView style={styles.safe} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><View style={styles.header}><BrandMark /><Pressable onPress={() => router.push("/(tabs)/search" as any)}><MaterialIcons name="search" size={23} color={PALETTE.ink} /></Pressable></View><Text style={styles.eyebrow}>TEXAS EVENT DISCOVERY</Text><Text style={styles.title}>FIND WHAT{`\n`}MOVES YOU.</Text><View style={styles.search}><MaterialIcons name="search" color={PALETTE.muted} size={19}/><TextInput value={query} onChangeText={setQuery} placeholder="Search artist, venue or city" placeholderTextColor={PALETTE.muted} style={styles.searchInput}/></View><Text style={styles.filterLabel}>CATEGORY</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{["All", ...CATEGORIES].map((item) => <Pressable onPress={() => setCategory(item)} key={item} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item.toUpperCase()}</Text></Pressable>)}</ScrollView><Text style={styles.filterLabel}>LOCATION</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{["All", ...CITIES].map((item) => <Pressable onPress={() => setCity(item)} key={item} style={[styles.chip, city === item && styles.chipActive]}><Text style={[styles.chipText, city === item && styles.chipTextActive]}>{item.toUpperCase()}</Text></Pressable>)}</ScrollView><View style={styles.resultBar}><Text style={styles.resultText}>{events.length} DEMO EVENT{events.length === 1 ? "" : "S"}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6 }}>{["Recommended", "Date", "Price Low → High", "Price High → Low"].map((item) => <Pressable onPress={() => setSort(item)} key={item} style={[styles.sort, sort === item && styles.sortActive]}><Text style={[styles.sortText, sort === item && styles.sortTextActive]}>{item}</Text></Pressable>)}</ScrollView></View><View style={styles.list}>{events.length ? events.map((event) => <EventCard key={event.id} event={event} compact />) : <EmptyState title="No matching demo records" body="Try another city, category or a broader search term. VÉLORA only shows the catalog records it can verify." actionLabel="CLEAR FILTERS" onAction={() => { setQuery(""); setCategory("All"); setCity("All"); }} />}</View></ScrollView></SafeAreaView></AppShell>;
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:PALETTE.cream},page:{padding:20,paddingBottom:110},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:42},eyebrow:{fontSize:10,fontWeight:"800",letterSpacing:1.5,color:PALETTE.champagne},title:{fontFamily:"Georgia",color:PALETTE.ink,fontSize:39,lineHeight:40,letterSpacing:-1,marginTop:8},search:{height:52,marginTop:24,backgroundColor:PALETTE.white,borderColor:PALETTE.border,borderWidth:1,borderRadius:4,alignItems:"center",flexDirection:"row",paddingHorizontal:14},searchInput:{flex:1,paddingLeft:10,color:PALETTE.ink,fontSize:13},filterLabel:{color:PALETTE.muted,fontWeight:"800",fontSize:9,letterSpacing:1.2,marginTop:24,marginBottom:9},chips:{gap:7,paddingRight:20},chip:{borderColor:PALETTE.border,borderWidth:1,paddingHorizontal:12,paddingVertical:9,borderRadius:20,backgroundColor:PALETTE.white},chipActive:{backgroundColor:PALETTE.ink,borderColor:PALETTE.ink},chipText:{fontSize:9,fontWeight:"800",letterSpacing:.5,color:PALETTE.ink},chipTextActive:{color:PALETTE.cream},resultBar:{marginTop:30,gap:10},resultText:{fontSize:10,color:PALETTE.muted,fontWeight:"800",letterSpacing:1},sort:{paddingHorizontal:10,paddingVertical:8,backgroundColor:PALETTE.nude,borderRadius:3},sortActive:{backgroundColor:PALETTE.champagne},sortText:{fontSize:9,fontWeight:"700",color:PALETTE.ink},sortTextActive:{fontWeight:"800"},list:{marginTop:16}
});
