import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { AppShell, DemoPill, OutlineButton, PALETTE, PageHeader, PrimaryButton } from "@/components/velora-ui";
import { trpc } from "@/lib/trpc";

export default function OrderConfirmation(){const {number,eventSlug}=useLocalSearchParams<{number:string;eventSlug:string}>();const event=trpc.marketplace.event.useQuery({slug:eventSlug||""},{enabled:!!eventSlug});return <AppShell><SafeAreaView style={styles.safe} edges={["top","left","right"]}><PageHeader title="ORDER CONFIRMATION"/><ScrollView contentContainerStyle={styles.page}><View style={styles.sparkle}><MaterialIcons name="auto-awesome" size={32} color={PALETTE.champagne}/></View><Text style={styles.title}>YOU’RE GOING.{`\n`}<Text style={styles.subtitle}>IN DEMO MODE.</Text></Text><Text style={styles.copy}>Your VÉLORA test order has been recorded. No real payment was captured and no actual ticket has been delivered.</Text><View style={styles.order}><View style={styles.orderTop}><DemoPill/><Text style={styles.orderNumber}>{number}</Text></View><Text style={styles.orderTitle}>{event.data?.event.title||"VÉLORA DEMO EVENT"}</Text><Text style={styles.orderMeta}>{event.data?.event.venue||"Verified demo venue"} · {event.data?.event.city||"Texas"}</Text><View style={styles.status}><MaterialIcons name="check-circle-outline" size={20} color={PALETTE.success}/><View><Text style={styles.statusTitle}>DEMO ORDER READY</Text><Text style={styles.statusText}>In a live environment, a verified delivery status would appear here. This preview does not issue a ticket.</Text></View></View></View><View style={styles.actions}><PrimaryButton label="VIEW ACCOUNT" onPress={()=>router.replace("/(tabs)/account" as any)} icon="arrow-forward"/><OutlineButton label="CONTACT SUPPORT" onPress={()=>router.push("/contact" as any)} icon="mail-outline"/></View><View style={styles.note}><Text style={styles.noteTitle}>WHAT HAPPENS NEXT?</Text><Text style={styles.noteText}>Nothing financial or ticket-related occurs in DEMO MODE. Before launch, connect a payment provider, authorized inventory source and compliant delivery workflow.</Text></View></ScrollView></SafeAreaView></AppShell>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:PALETTE.cream},page:{padding:25,paddingTop:48},sparkle:{height:64,width:64,borderRadius:32,backgroundColor:PALETTE.ink,alignItems:"center",justifyContent:"center",marginBottom:21},title:{fontFamily:"Georgia",fontSize:37,lineHeight:40,letterSpacing:-1,color:PALETTE.ink},subtitle:{color:PALETTE.champagne},copy:{fontSize:13,lineHeight:19,color:PALETTE.muted,marginTop:17,maxWidth:330},order:{marginTop:30,backgroundColor:PALETTE.white,borderWidth:1,borderColor:PALETTE.border,padding:18},orderTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},orderNumber:{fontSize:10,fontWeight:"800",letterSpacing:.7,color:PALETTE.ink},orderTitle:{fontFamily:"Georgia",fontSize:22,color:PALETTE.ink,marginTop:18},orderMeta:{color:PALETTE.muted,fontSize:11,marginTop:6},status:{marginTop:20,paddingTop:15,borderTopWidth:1,borderColor:PALETTE.border,flexDirection:"row",gap:9},statusTitle:{fontSize:10,fontWeight:"800",letterSpacing:.7,color:PALETTE.success},statusText:{fontSize:10,lineHeight:15,color:PALETTE.muted,marginTop:4,maxWidth:250},actions:{gap:10,marginTop:18},note:{marginTop:30,padding:16,backgroundColor:PALETTE.nude,borderLeftWidth:3,borderColor:PALETTE.champagne},noteTitle:{fontSize:10,fontWeight:"800",letterSpacing:.8,color:PALETTE.ink},noteText:{fontSize:11,lineHeight:16,color:PALETTE.muted,marginTop:7}});
